import type { Location } from "./locations";

/**
 * Further regions: central and western Queensland, and northern New South Wales.
 * All are long trips from the Sherwood depot, so every page says collections are arranged in advance.
 */
export const northernNswData: Omit<Location, "heroImage">[] = [
  {
    slug: "tweed",
    name: "Tweed",
    state: "NSW",
    region: "Northern New South Wales",
    tier: "extended",
    council: "Tweed Shire Council",
    distanceKm: "100–130",
    geo: { latitude: -28.1788, longitude: 153.5469 },
    suburbs: ["Tweed Heads", "Tweed Heads South", "Banora Point", "Terranora", "Kingscliff", "Chinderah", "Casuarina", "Cabarita Beach", "Pottsville", "Murwillumbah", "Tumbulgum", "Uki"],
    access: "Tweed is just over the border from the Gold Coast, reached from Sherwood on the Pacific Motorway (M1), about an hour and a half south.",
    vehicles: "Border-town second cars, cars from units and holiday rentals, hinterland utes and 4WDs around Murwillumbah.",
    pickup: "Tweed pickups are booked in advance and often combined with Gold Coast runs, so we confirm a day and window with you.",
    about: [
      "The Tweed sits directly south of the Gold Coast, with Tweed Heads running into Coolangatta at the border. It spreads from the beach towns of Kingscliff and Cabarita Beach to the Tweed Valley around Murwillumbah and Uki.",
      "A lot of people here live on one side of the border and work on the other, and cars end up with Queensland or New South Wales plates and a mix of paperwork. We buy them either way, running or not, and tell you what is needed once we have the details.",
      "Because the Tweed is close to the Gold Coast, we can often fit it into a southern run. We still confirm a day with you when we quote rather than promising same-day.",
    ],
    faqs: [
      {
        question: "Do you collect cars with NSW plates in Tweed Heads and Kingscliff?",
        answer: "Yes. We buy vehicles registered in New South Wales or Queensland, and unregistered ones. Tell us the plate state and whether it is still registered when you request the quote.",
      },
      {
        question: "Is Murwillumbah included in your Tweed service area?",
        answer: "Yes. Murwillumbah, Uki, Tumbulgum and the Tweed Valley are included, along with Tweed Heads, Kingscliff, Pottsville and Cabarita Beach. Call 0422 360 534 to book a day.",
      },
    ],
    nearby: ["gold-coast", "byron", "scenic-rim", "logan"],
  },
  {
    slug: "byron",
    name: "Byron",
    state: "NSW",
    region: "Northern New South Wales",
    tier: "extended",
    council: "Byron Shire Council",
    distanceKm: "150–180",
    geo: { latitude: -28.6474, longitude: 153.602 },
    suburbs: ["Byron Bay", "Suffolk Park", "Bangalow", "Mullumbimby", "Brunswick Heads", "Ocean Shores", "New Brighton", "South Golden Beach", "Billinudgel", "Federal", "Main Arm", "Ewingsdale"],
    access: "Byron is reached from Sherwood on the Pacific Motorway past the Gold Coast and Tweed, about two and a half hours south.",
    vehicles: "Older campervans and vans, hatchbacks, hinterland utes and cars left behind by travellers and renters.",
    pickup: "Byron pickups are arranged in advance and grouped with other Northern Rivers collections.",
    about: [
      "Byron Shire runs from the beaches of Byron Bay and Brunswick Heads to the hinterland villages of Bangalow, Federal and Mullumbimby. It is a popular holiday and lifestyle area with many rentals, shared houses and acreage blocks.",
      "That means a distinct mix of vehicles: ageing vans and campervans, small cars owned by travellers who have moved on, and farm and lifestyle-block utes. We buy them in any condition and tow them away free.",
      "Streets in Byron Bay can be narrow and busy, and some properties have steep or gravel driveways. Tell us about access when you request the quote and we will plan the right truck and a day.",
    ],
    faqs: [
      {
        question: "Do you buy old vans and campervans in Byron Bay?",
        answer: "Yes. We buy vans and campervans in any condition, registered or not, running or not. Tell us the make, year and what works, and we quote before we send a truck.",
      },
      {
        question: "Can you collect from Mullumbimby, Bangalow and the hinterland?",
        answer: "Yes. Mullumbimby, Bangalow, Federal, Main Arm and the rest of the Byron hinterland are included. Pickups are booked in advance, so call 0422 360 534 to confirm a day.",
      },
    ],
    nearby: ["tweed", "ballina", "lismore", "kyogle"],
  },
  {
    slug: "ballina",
    name: "Ballina",
    state: "NSW",
    region: "Northern New South Wales",
    tier: "extended",
    council: "Ballina Shire Council",
    distanceKm: "200–230",
    geo: { latitude: -28.8662, longitude: 153.5654 },
    suburbs: ["Ballina", "East Ballina", "Lennox Head", "Skennars Head", "Alstonville", "Wollongbar", "Wardell", "Cumbalum", "Pimlico", "Teven", "Newrybar", "Tintenbar"],
    access: "Ballina is reached from Sherwood on the Pacific Motorway and Pacific Highway, about three hours south.",
    vehicles: "Family cars, utes and 4WDs from coastal suburbs, plus farm and macadamia-country vehicles around Alstonville.",
    pickup: "Ballina pickups are booked in advance, and we confirm a day when we quote.",
    about: [
      "Ballina Shire covers the river town of Ballina, the beach community of Lennox Head and the plateau around Alstonville and Wollongbar, set among macadamia and cane country.",
      "It is a mix of coastal suburbs and farmland, so we hear about everyday cars that failed a roadworthy or have outlived their value, as well as working utes and 4WDs from rural properties.",
      "Ballina is a long trip from our depot, so we plan the day with you and, where possible, combine it with other Northern Rivers collections.",
    ],
    faqs: [
      {
        question: "Do you collect from Lennox Head and Alstonville?",
        answer: "Yes. Lennox Head, Alstonville, Wollongbar, Wardell, Skennars Head and Ballina itself are included. Pickups are booked in advance, so call 0422 360 534 and we will confirm a day.",
      },
      {
        question: "What happens to my NSW-registered car after you buy it?",
        answer: "It is taken to a licensed dismantling and recycling facility. After the sale you should tell Service NSW that you have sold or disposed of the vehicle, and we will explain what you need.",
      },
    ],
    nearby: ["byron", "lismore", "richmond-valley"],
  },
  {
    slug: "lismore",
    name: "Lismore",
    state: "NSW",
    region: "Northern New South Wales",
    tier: "extended",
    council: "Lismore City Council",
    distanceKm: "190–220",
    geo: { latitude: -28.8142, longitude: 153.2776 },
    suburbs: ["Lismore", "Goonellabah", "South Lismore", "East Lismore", "Lismore Heights", "Girards Hill", "Nimbin", "Clunes", "Bexhill", "Dunoon", "Modanville", "Rock Valley"],
    access: "Lismore is reached from Sherwood on the Pacific Motorway and Pacific Highway then inland from Ballina, or via the Mount Lindesay Highway and Kyogle, about three hours south.",
    vehicles: "Family cars, utes and flood-affected vehicles from Lismore, Goonellabah and the Nimbin hinterland.",
    pickup: "Lismore pickups are booked in advance and confirmed with a day and window when we quote.",
    about: [
      "Lismore is the main city of the Northern Rivers, on the Wilsons River, with Goonellabah to the east and the hinterland village of Nimbin to the north-west.",
      "The Lismore area was badly affected by the February and March 2022 floods, and flood-damaged vehicles are a regular enquiry. We buy flood-affected cars and utes like any other vehicle, running or not, and give you a price before we send a truck.",
      "Because Lismore is a long trip from our depot, collections are arranged ahead. If you have several vehicles, for example from a clean-up, tell us and we will quote them together.",
    ],
    faqs: [
      {
        question: "Do you buy flood-damaged cars in Lismore?",
        answer: "Yes. We buy flood-affected vehicles in any condition. Tell us the make, model, year and how long it was under water, and we quote before we send a truck.",
      },
      {
        question: "Do you collect from Goonellabah and Nimbin?",
        answer: "Yes. Goonellabah, South Lismore, Nimbin, Clunes, Dunoon and the rest of the Lismore area are included. Call 0422 360 534 and we will confirm a day.",
      },
    ],
    nearby: ["byron", "ballina", "richmond-valley", "kyogle"],
  },
  {
    slug: "richmond-valley",
    name: "Richmond Valley",
    state: "NSW",
    region: "Northern New South Wales",
    tier: "extended",
    council: "Richmond Valley Council",
    distanceKm: "230–270",
    geo: { latitude: -28.8667, longitude: 153.05 },
    suburbs: ["Casino", "Evans Head", "Coraki", "Woodburn", "Broadwater", "Rappville", "Codrington", "Wyrallah", "Swan Bay", "Dungarubba", "Whiporie", "Bora Ridge"],
    access: "The Richmond Valley is reached from Sherwood via the Pacific Highway to Woodburn, or inland via Kyogle to Casino, about three and a half hours south.",
    vehicles: "Farm utes, light trucks, 4WDs and older cars from Casino, Evans Head and the river towns.",
    pickup: "Richmond Valley pickups are arranged in advance and grouped with Northern Rivers runs.",
    about: [
      "The Richmond Valley is centred on Casino, a major cattle and meat-processing town on the Richmond River, with Evans Head on the coast and the river villages of Coraki and Woodburn.",
      "Cattle country means working vehicles: utes, small trucks and 4WDs. When one is no longer worth repairing it is usually parked up rather than scrapped, and we buy them in any condition and tow them out.",
      "The valley is a long way from our depot, so we plan collections and confirm a day with you. Combining a few vehicles in one trip makes it easier to arrange.",
    ],
    faqs: [
      {
        question: "Do you collect from Casino and Evans Head?",
        answer: "Yes. Casino, Evans Head, Coraki, Woodburn, Broadwater and the other Richmond Valley towns are included. Call 0422 360 534 and we will confirm a day.",
      },
      {
        question: "Can you collect a vehicle from a farm paddock near Casino?",
        answer: "Often yes. Tell us the ground conditions, gate size and how far the vehicle is from the road when you request the quote.",
      },
    ],
    nearby: ["lismore", "ballina", "clarence-valley", "kyogle"],
  },
  {
    slug: "kyogle",
    name: "Kyogle",
    state: "NSW",
    region: "Northern New South Wales",
    tier: "extended",
    council: "Kyogle Council",
    distanceKm: "150–190",
    geo: { latitude: -28.6192, longitude: 153.0088 },
    suburbs: ["Kyogle", "Woodenbong", "Bonalbo", "Wiangaree", "Mallanganee", "Tabulam", "Urbenville", "Old Bonalbo", "Muli Muli", "Geneva", "Cawongla", "Tooloom"],
    access: "Kyogle is reached from Sherwood on the Mount Lindesay Highway through Beaudesert and Rathdowney, or via the Pacific Highway and Lismore, about two and a half hours south.",
    vehicles: "Farm utes, 4WDs, older work trucks and cars from rural blocks.",
    pickup: "Kyogle pickups are booked in advance, often combined with Scenic Rim or Lismore runs.",
    about: [
      "Kyogle Council covers the upper Richmond Valley and the ranges along the Queensland border, with the main town of Kyogle and villages such as Woodenbong, Bonalbo and Urbenville.",
      "It is dairy, beef and timber country, with a lot of rural properties and long driveways. We are used to collecting from gates, paddocks and gravel tracks.",
      "Woodenbong and the northern end of the council area are close to the Queensland Scenic Rim, so we can often pair them with a Scenic Rim collection. We still confirm a day with you when we quote.",
    ],
    faqs: [
      {
        question: "Do you collect from Woodenbong and Bonalbo?",
        answer: "Yes. Woodenbong, Bonalbo, Urbenville, Tabulam and the rest of the Kyogle area are included. Call 0422 360 534 and we will confirm a day.",
      },
      {
        question: "Is Kyogle covered even though it is in New South Wales?",
        answer: "Yes. We collect in northern New South Wales as well as Queensland. Towing is free when we buy the vehicle.",
      },
    ],
    nearby: ["lismore", "richmond-valley", "tenterfield", "scenic-rim"],
  },
  {
    slug: "clarence-valley",
    name: "Clarence Valley",
    state: "NSW",
    region: "Northern New South Wales",
    tier: "extended",
    council: "Clarence Valley Council",
    distanceKm: "330–370",
    geo: { latitude: -29.69, longitude: 152.9326 },
    suburbs: ["Grafton", "South Grafton", "Yamba", "Maclean", "Iluka", "Ulmarra", "Brooms Head", "Wooli", "Glenreagh", "Lawrence", "Gulmarrad", "Copmanhurst"],
    access: "The Clarence Valley is reached from Sherwood on the Pacific Highway, about four hours south.",
    vehicles: "Family cars, utes and 4WDs from Grafton, the river towns and coastal villages.",
    pickup: "Clarence Valley pickups are booked in advance, and we confirm a day with you.",
    about: [
      "The Clarence Valley is the largest council area on the New South Wales north coast, centred on the river city of Grafton and including Yamba, Maclean, Iluka and the villages along the Clarence River.",
      "It is a mix of river towns, coastal communities and farmland, so we hear about everyday cars and utes that no longer pass a roadworthy, along with working vehicles from cane and cattle properties.",
      "Grafton is about four hours from our depot, so collections are planned. If you have more than one vehicle, tell us and we will quote and collect them together.",
    ],
    faqs: [
      {
        question: "Do you collect from Grafton, Yamba and Maclean?",
        answer: "Yes. Grafton, Yamba, Maclean, Iluka, Ulmarra and nearby Clarence Valley towns are included. Call 0422 360 534 and we will confirm a day.",
      },
      {
        question: "Is towing free from Grafton?",
        answer: "Yes. Towing is free whenever we agree to buy the vehicle, however far the trip. The quoted price is the amount you receive.",
      },
    ],
    nearby: ["richmond-valley", "coffs-harbour", "lismore"],
  },
  {
    slug: "tenterfield",
    name: "Tenterfield",
    state: "NSW",
    region: "Northern New South Wales",
    tier: "extended",
    council: "Tenterfield Shire Council",
    distanceKm: "290–330",
    geo: { latitude: -29.0494, longitude: 152.0187 },
    suburbs: ["Tenterfield", "Urbenville", "Drake", "Jennings", "Mingoola", "Torrington", "Liston", "Legume", "Bolivia", "Sandy Flat", "Boonoo Boonoo", "Willsons Downfall"],
    access: "Tenterfield is reached from Sherwood on the Mount Lindesay Highway, or via Warwick and Stanthorpe on the New England Highway, about three and a half hours south-west.",
    vehicles: "Farm utes, 4WDs and older cars from rural properties on the New England Tableland.",
    pickup: "Tenterfield pickups are booked in advance, often with Southern Downs or Kyogle runs.",
    about: [
      "Tenterfield sits on the New England Highway just over the border from Stanthorpe, on the northern end of the New England Tableland. The shire runs from Tenterfield town to Urbenville, Drake and the border ranges.",
      "It is grazing and fruit country with plenty of older utes and 4WDs. We buy them in any condition and tow them out, including from properties with long driveways and gates.",
      "Because Tenterfield is close to the Granite Belt, we can sometimes pair it with a Southern Downs trip. We still confirm a day with you when we quote.",
    ],
    faqs: [
      {
        question: "Do you collect from Tenterfield and Drake?",
        answer: "Yes. Tenterfield, Drake, Urbenville, Jennings, Torrington and the rest of the Tenterfield Shire are included. Call 0422 360 534 and we will confirm a day.",
      },
      {
        question: "Can you collect a Queensland-registered car in Tenterfield?",
        answer: "Yes. We buy vehicles registered in Queensland or New South Wales, or unregistered. Tell us the plate state when you request the quote.",
      },
    ],
    nearby: ["kyogle", "southern-downs", "glen-innes-severn"],
  },
  {
    slug: "glen-innes-severn",
    name: "Glen Innes Severn",
    state: "NSW",
    region: "Northern New South Wales",
    tier: "extended",
    council: "Glen Innes Severn Council",
    distanceKm: "420–460",
    geo: { latitude: -29.7358, longitude: 151.7394 },
    suburbs: ["Glen Innes", "Emmaville", "Deepwater", "Glencoe", "Dundee", "Wellingrove", "Red Range", "Pinkett", "Matheson", "Stannum", "Tent Hill", "Wytaliba"],
    access: "Glen Innes is reached from Sherwood on the New England Highway through Warwick, Stanthorpe and Tenterfield, about five hours south-west.",
    vehicles: "Farm utes, 4WDs and light trucks from the tableland, and older cars from town.",
    pickup: "Glen Innes pickups are booked well in advance and often combined with other New England collections.",
    about: [
      "Glen Innes Severn covers the town of Glen Innes, known for its Celtic heritage, and the surrounding tableland villages of Emmaville, Deepwater and Glencoe on the New England Highway.",
      "It is high, cold grazing country with plenty of working vehicles. We buy utes, 4WDs and trucks in any condition and tow them out for free when we buy.",
      "The trip from our depot is long, so we plan collections and confirm a day with you. Sending the details of every vehicle together lets us quote and arrange them in one trip.",
    ],
    faqs: [
      {
        question: "Do you collect from Glen Innes and Emmaville?",
        answer: "Yes. Glen Innes, Emmaville, Deepwater, Glencoe and nearby villages are included. Call 0422 360 534 and we will confirm a day.",
      },
      {
        question: "How far in advance should I book a pickup in Glen Innes?",
        answer: "As early as you can. Send the vehicle details and we reply with a price and a proposed day; booking early makes it easier to combine with other New England collections.",
      },
    ],
    nearby: ["tenterfield", "inverell", "armidale"],
  },
  {
    slug: "inverell",
    name: "Inverell",
    state: "NSW",
    region: "Northern New South Wales",
    tier: "extended",
    council: "Inverell Shire Council",
    distanceKm: "470–510",
    geo: { latitude: -29.7743, longitude: 151.1124 },
    suburbs: ["Inverell", "Ashford", "Delungra", "Yetman", "Oakwood", "Gilgai", "Wallangra", "Nullamanna", "Copeton", "Graman", "Byron Creek", "Tingha"],
    access: "Inverell is reached from Sherwood via Warwick and Goondiwindi or the New England Highway and Glen Innes, about five and a half to six hours south-west.",
    vehicles: "Farm utes, trucks and 4WDs from grain, beef and sapphire-country properties.",
    pickup: "Inverell pickups are booked well in advance and confirmed with a day when we quote.",
    about: [
      "Inverell, known as the Sapphire City, is the centre of a large shire on the north-west slopes of New South Wales, with Ashford, Delungra, Yetman and Tingha around it.",
      "It is mixed farming country with plenty of utes, trucks and 4WDs, and some of them have done huge distances. We buy them in any condition and tow them away free.",
      "Inverell is one of the furthest points on our list, so collections are planned in advance and combined with nearby jobs where we can.",
    ],
    faqs: [
      {
        question: "Do you collect from Inverell and Ashford?",
        answer: "Yes. Inverell, Ashford, Delungra, Yetman, Tingha and the other Inverell Shire towns are included. Call 0422 360 534 and we will confirm a day.",
      },
      {
        question: "Can you collect more than one vehicle from my property near Inverell?",
        answer: "Yes. List every vehicle with its make, model, year and condition and we will quote and collect them together.",
      },
    ],
    nearby: ["glen-innes-severn", "goondiwindi", "armidale"],
  },
  {
    slug: "coffs-harbour",
    name: "Coffs Harbour",
    state: "NSW",
    region: "Northern New South Wales",
    tier: "extended",
    council: "Coffs Harbour City Council",
    distanceKm: "450–490",
    geo: { latitude: -30.2963, longitude: 153.1135 },
    suburbs: ["Coffs Harbour", "Woolgoolga", "Sawtell", "Toormina", "Korora", "Boambee", "Bonville", "Emerald Beach", "Moonee Beach", "Coramba", "Nana Glen", "Corindi Beach"],
    access: "Coffs Harbour is reached from Sherwood on the Pacific Highway, about five and a half hours south.",
    vehicles: "Family cars, second cars, utes and holiday-home vehicles from coastal suburbs.",
    pickup: "Coffs Harbour pickups are booked well in advance, often combined with Clarence Valley collections.",
    about: [
      "Coffs Harbour is the largest city between Newcastle and the Gold Coast, with the coastal suburbs of Sawtell, Toormina and Woolgoolga and the hinterland around Coramba and Nana Glen.",
      "As a big coastal city it has plenty of second cars, vehicles left after a move and older cars that no longer pass a roadworthy. We buy them in any condition and tow them free.",
      "Coffs Harbour is a long drive from our depot, so we plan collections and confirm a day with you. Tell us if you have more than one vehicle and we will quote them together.",
    ],
    faqs: [
      {
        question: "Do you collect from Sawtell, Toormina and Woolgoolga?",
        answer: "Yes. Sawtell, Toormina, Woolgoolga, Korora, Bonville and the rest of the Coffs Harbour area are included. Call 0422 360 534 and we will confirm a day.",
      },
      {
        question: "How soon can you collect in Coffs Harbour?",
        answer: "Coffs Harbour pickups are booked in advance rather than same-day. We reply to your quote with a proposed day and window.",
      },
    ],
    nearby: ["clarence-valley", "armidale"],
  },
  {
    slug: "armidale",
    name: "Armidale",
    state: "NSW",
    region: "Northern New South Wales",
    tier: "extended",
    council: "Armidale Regional Council",
    distanceKm: "540–600",
    geo: { latitude: -30.5128, longitude: 151.6677 },
    suburbs: ["Armidale", "Guyra", "Ebor", "Wollomombi", "Hillgrove", "Black Mountain", "Kellys Plains", "Invergowrie", "Ben Lomond", "Metz", "Dangarsleigh", "Jeogla"],
    access: "Armidale is reached from Sherwood on the New England Highway through Warwick and Tenterfield, about six hours south-west.",
    vehicles: "Student and second cars from Armidale, plus farm utes and 4WDs from the tableland.",
    pickup: "Armidale pickups are booked well in advance and confirmed with a day when we quote.",
    about: [
      "Armidale is the main city of the New England Tableland and a university town, with Guyra to the north and the gorge country around Ebor and Wollomombi to the east.",
      "A university town produces a particular kind of car: a student's old hatchback that no longer passes a roadworthy, or a vehicle left behind at the end of a degree. Rural properties around it add farm utes and 4WDs. We buy them in any condition.",
      "Armidale is the furthest point on our list, so collections are arranged well in advance and combined with other New England jobs where we can.",
    ],
    faqs: [
      {
        question: "Do you collect from Armidale and Guyra?",
        answer: "Yes. Armidale, Guyra, Ebor, Wollomombi and nearby towns are included. Call 0422 360 534 and we will confirm a day.",
      },
      {
        question: "Do you buy students' old cars in Armidale?",
        answer: "Yes. We buy cars in any condition, registered or not. Send the make, model, year and suburb and we quote before we send a truck.",
      },
    ],
    nearby: ["glen-innes-severn", "coffs-harbour", "inverell"],
  },
];

export const centralQldData: Omit<Location, "heroImage">[] = [
  {
    slug: "north-burnett",
    name: "North Burnett",
    region: "Burnett",
    tier: "extended",
    council: "North Burnett Regional Council",
    distanceKm: "330–420",
    geo: { latitude: -25.6333, longitude: 151.6167 },
    suburbs: ["Gayndah", "Mundubbera", "Eidsvold", "Biggenden", "Monto", "Mount Perry", "Ban Ban Springs", "Abercorn", "Cania"],
    access: "The North Burnett is reached from Sherwood via Kingaroy and the Burnett Highway through Murgon, about four and a half to five hours north-west.",
    vehicles: "Farm utes, trucks and 4WDs from citrus orchards and cattle properties.",
    pickup: "North Burnett pickups are booked well in advance, often combined with South Burnett or Bundaberg runs.",
    about: [
      "The North Burnett centres on Gayndah, Mundubbera, Eidsvold, Biggenden and Monto, along the Burnett River. It is citrus, beef and grain country with long distances between towns.",
      "That means a steady supply of farm utes, trucks and 4WDs that are old and heavily used. We buy them in any condition and tow them away free.",
      "The region is a long way from our depot, so we plan collections and confirm a day with you. Combining several vehicles in one trip makes it far easier to arrange.",
    ],
    faqs: [
      {
        question: "Do you collect from Gayndah and Mundubbera?",
        answer: "Yes. Gayndah, Mundubbera, Eidsvold, Biggenden, Monto and nearby North Burnett towns are included. Call 0422 360 534 and we will confirm a day.",
      },
      {
        question: "Can you collect from an orchard or farm track?",
        answer: "Often yes. Tell us about the ground, the gate and the distance from the road when you request the quote.",
      },
    ],
    nearby: ["south-burnett", "gympie", "bundaberg", "banana"],
  },
  {
    slug: "goondiwindi",
    name: "Goondiwindi",
    region: "Darling Downs",
    tier: "extended",
    council: "Goondiwindi Regional Council",
    distanceKm: "340–380",
    geo: { latitude: -28.5473, longitude: 150.3071 },
    suburbs: ["Goondiwindi", "Inglewood", "Texas", "Yelarbon", "Bungunya", "Talwood", "Toobeah", "Waggamba", "Billa Billa", "Coolmunda"],
    access: "Goondiwindi is reached from Sherwood on the Cunningham Highway through Ipswich and Warwick, about four and a half hours south-west.",
    vehicles: "Farm utes, trucks and 4WDs from cotton and grain country, and cars from the border towns.",
    pickup: "Goondiwindi pickups are booked in advance and often combined with Southern Downs or Toowoomba runs.",
    about: [
      "Goondiwindi sits on the Macintyre River on the New South Wales border, in cotton, grain and cattle country, with Inglewood, Texas and Yelarbon along the Cunningham and Barwon highways.",
      "Border towns collect vehicles with Queensland and New South Wales plates. We buy them in any condition, registered or not, and explain the paperwork once we know the plate state.",
      "Goondiwindi is a long trip from our depot, so collections are planned. Tell us if there are several vehicles and we will quote them together.",
    ],
    faqs: [
      {
        question: "Do you collect from Goondiwindi, Inglewood and Texas?",
        answer: "Yes. Goondiwindi, Inglewood, Texas, Yelarbon, Toobeah and nearby towns are included. Call 0422 360 534 and we will confirm a day.",
      },
      {
        question: "Do you buy NSW-registered vehicles near the border?",
        answer: "Yes. We buy Queensland- and New South Wales-registered vehicles, and unregistered ones. Tell us the plate state when you request the quote.",
      },
    ],
    nearby: ["southern-downs", "toowoomba", "western-downs", "inverell"],
  },
  {
    slug: "maranoa",
    name: "Maranoa",
    region: "South West Queensland",
    tier: "extended",
    council: "Maranoa Regional Council",
    distanceKm: "470–540",
    geo: { latitude: -26.5667, longitude: 148.7833 },
    suburbs: ["Roma", "Mitchell", "Injune", "Surat", "Wallumbilla", "Yuleba", "Mungallala", "Amby", "Jackson", "Muckadilla"],
    access: "The Maranoa is reached from Sherwood on the Warrego Highway through Toowoomba, Dalby and Miles to Roma, about six hours west.",
    vehicles: "Utes, 4WDs, light trucks and work vehicles from cattle properties and gas-field work.",
    pickup: "Maranoa pickups are arranged well in advance, and we confirm the day and route with you.",
    about: [
      "The Maranoa is centred on Roma, home to the Roma Saleyards, one of the biggest cattle saleyards in the country, with Mitchell, Injune and Surat around it. It is cattle and gas country on the Warrego Highway.",
      "Work vehicles are the norm: utes, 4WDs and light trucks that have covered huge distances. When one is finished it usually still has value in its parts and metal, and we buy it in any condition.",
      "Roma is a long way from our depot, so we plan collections and often combine them with Western Downs jobs. Tell us if you have several vehicles and we will quote them together.",
    ],
    faqs: [
      {
        question: "Do you collect from Roma, Mitchell and Injune?",
        answer: "Yes. Roma, Mitchell, Injune, Surat, Wallumbilla and nearby Maranoa towns are included. Call 0422 360 534 and we will confirm a day.",
      },
      {
        question: "Can you collect work utes from a worksite near Roma?",
        answer: "Yes. Tell us the location, the make, model, year and condition of each vehicle, and who can give access, and we will quote before we send a truck.",
      },
    ],
    nearby: ["western-downs", "balonne", "banana"],
  },
  {
    slug: "balonne",
    name: "Balonne",
    region: "South West Queensland",
    tier: "extended",
    council: "Balonne Shire Council",
    distanceKm: "490–560",
    geo: { latitude: -28.0333, longitude: 148.5833 },
    suburbs: ["St George", "Dirranbandi", "Bollon", "Thallon", "Nindigully", "Hebel", "Mungindi", "Weengallon", "Boolba"],
    access: "Balonne is reached from Sherwood via Goondiwindi or Roma, about six and a half hours west and south-west.",
    vehicles: "Utes, 4WDs and trucks from cotton and cattle properties along the Balonne River.",
    pickup: "Balonne pickups are booked well in advance, and we confirm a day with you.",
    about: [
      "Balonne Shire, around St George and Dirranbandi, is irrigated cotton and grazing country along the Balonne River in south-west Queensland.",
      "Cotton and cattle farming means working utes, trucks and 4WDs that have been used hard. We buy them in any condition and tow them out free.",
      "Balonne is one of the longest trips on our list, so collections are planned and combined with other south-west jobs where we can.",
    ],
    faqs: [
      {
        question: "Do you collect from St George and Dirranbandi?",
        answer: "Yes. St George, Dirranbandi, Bollon, Thallon and the surrounding Balonne towns are included. Call 0422 360 534 and we will confirm a day.",
      },
      {
        question: "Is a single vehicle worth collecting this far out?",
        answer: "It can be. We quote before we send a truck and towing is free if we buy. Collections are easier to arrange when we can combine them, so tell us about any other vehicles too.",
      },
    ],
    nearby: ["goondiwindi", "maranoa", "western-downs"],
  },
  {
    slug: "gladstone",
    name: "Gladstone",
    region: "Capricorn",
    tier: "extended",
    council: "Gladstone Regional Council",
    distanceKm: "520–580",
    geo: { latitude: -23.8427, longitude: 151.2555 },
    suburbs: ["Gladstone", "Tannum Sands", "Boyne Island", "Calliope", "Agnes Water", "Miriam Vale", "Mount Larcom", "Benaraby", "Clinton", "Kin Kora", "Sun Valley", "Toolooa"],
    access: "Gladstone is reached from Sherwood on the Bruce Highway, about six and a half hours north.",
    vehicles: "Work utes, 4WDs, family cars and fly-in/fly-out workers' second cars.",
    pickup: "Gladstone pickups are booked well in advance and often combined with Bundaberg or Rockhampton runs.",
    about: [
      "Gladstone is a major port and industrial city, with Tannum Sands and Boyne Island to the south, Calliope inland and Agnes Water to the north.",
      "A working city means plenty of utes and 4WDs, and workers who leave town and need to sell a vehicle quickly. We buy them in any condition and tow them free.",
      "Gladstone is a long trip from our depot, so collections are planned in advance. If you are leaving town and need a date, tell us when you request the quote.",
    ],
    faqs: [
      {
        question: "Do you collect from Tannum Sands, Boyne Island and Calliope?",
        answer: "Yes. Tannum Sands, Boyne Island, Calliope, Agnes Water, Miriam Vale and the rest of the Gladstone region are included. Call 0422 360 534 and we will confirm a day.",
      },
      {
        question: "I am leaving Gladstone soon. Can you collect by a set date?",
        answer: "We will try. Tell us the date you need when you request the quote, and we will say whether we can meet it. Collections here are booked in advance.",
      },
    ],
    nearby: ["bundaberg", "banana", "rockhampton"],
  },
  {
    slug: "banana",
    name: "Banana",
    region: "Capricorn",
    tier: "extended",
    council: "Banana Shire Council",
    distanceKm: "560–650",
    geo: { latitude: -24.4045, longitude: 150.5106 },
    suburbs: ["Biloela", "Moura", "Taroom", "Theodore", "Baralaba", "Thangool", "Jambin", "Cracow", "Banana", "Wowan", "Dululu", "Goovigen"],
    access: "Banana Shire is reached from Sherwood on the Bruce Highway, then inland via Gladstone or Mount Larcom to Biloela, about seven hours north-west.",
    vehicles: "Farm and mine-support utes, trucks and 4WDs, plus older family cars.",
    pickup: "Banana Shire pickups are booked well in advance, often combined with Gladstone or Rockhampton runs.",
    about: [
      "Banana Shire is a big inland shire around Biloela, Moura, Taroom and Theodore, in cattle, cotton and coal country.",
      "Working vehicles dominate: utes, 4WDs and trucks that have done a lot of kilometres. We buy them in any condition and tow them away free when we buy.",
      "The shire is a very long trip from our depot, so collections are arranged in advance, and combining several vehicles makes them easier to arrange.",
    ],
    faqs: [
      {
        question: "Do you collect from Biloela and Moura?",
        answer: "Yes. Biloela, Moura, Taroom, Theodore, Baralaba and nearby Banana Shire towns are included. Call 0422 360 534 and we will confirm a day.",
      },
      {
        question: "Do you buy vehicles from mine-support work?",
        answer: "Yes. We buy utes, 4WDs and light trucks in any condition. Tell us the make, model, year and where the vehicles are parked.",
      },
    ],
    nearby: ["gladstone", "maranoa", "rockhampton", "north-burnett"],
  },
  {
    slug: "rockhampton",
    name: "Rockhampton",
    region: "Capricorn",
    tier: "extended",
    council: "Rockhampton Regional Council",
    distanceKm: "620–680",
    geo: { latitude: -23.378, longitude: 150.5069 },
    suburbs: ["Rockhampton", "North Rockhampton", "Gracemere", "Parkhurst", "Kawana", "Frenchville", "Norman Gardens", "Park Avenue", "Wandal", "Mount Morgan", "Alton Downs", "Bouldercombe"],
    access: "Rockhampton is reached from Sherwood on the Bruce Highway, about eight hours north.",
    vehicles: "Utes, 4WDs and trucks from cattle country, plus family cars from the city.",
    pickup: "Rockhampton pickups are booked well in advance, often combined with Gladstone or Capricorn Coast runs.",
    about: [
      "Rockhampton, on the Fitzroy River and the Tropic of Capricorn, calls itself the Beef Capital of Australia. Gracemere and Mount Morgan sit to the west and south.",
      "A big beef region and a regional city mean a lot of utes, 4WDs and trucks as well as everyday cars. We buy them in any condition and tow them away free.",
      "Rockhampton is one of the longest trips on our list. We plan the collection, confirm a day, and combine it with nearby jobs where we can, so tell us about any extra vehicles.",
    ],
    faqs: [
      {
        question: "Do you collect from Gracemere and Mount Morgan?",
        answer: "Yes. Gracemere, Mount Morgan, North Rockhampton, Parkhurst and the rest of the Rockhampton region are included. Call 0422 360 534 and we will confirm a day.",
      },
      {
        question: "Can I sell several vehicles from a Rockhampton property at once?",
        answer: "Yes, and it is the best way to make a long trip worthwhile. List every vehicle with make, model, year and condition and we quote them together.",
      },
    ],
    nearby: ["livingstone", "gladstone", "banana"],
  },
  {
    slug: "livingstone",
    name: "Livingstone",
    region: "Capricorn",
    tier: "extended",
    council: "Livingstone Shire Council",
    distanceKm: "650–710",
    geo: { latitude: -23.1333, longitude: 150.7333 },
    suburbs: ["Yeppoon", "Emu Park", "Cooee Bay", "Zilzie", "Lammermoor", "Keppel Sands", "Farnborough", "Marlborough", "Stanwell", "Mount Chalmers", "Taroomball", "Byfield"],
    access: "The Capricorn Coast is reached from Sherwood on the Bruce Highway to Rockhampton, then east to Yeppoon, about eight and a half hours north.",
    vehicles: "Coastal second cars, holiday-home vehicles, utes and 4WDs from the Capricorn Coast and hinterland.",
    pickup: "Livingstone pickups are booked well in advance and often combined with Rockhampton runs.",
    about: [
      "Livingstone Shire covers the Capricorn Coast: Yeppoon and Emu Park on Keppel Bay, the gateway to Great Keppel Island, plus Marlborough and Stanwell inland.",
      "A coastal lifestyle area means second cars, holiday-home vehicles and older cars that no longer pass a roadworthy, as well as hinterland utes and 4WDs. We buy them in any condition and tow them free.",
      "The Capricorn Coast is a very long trip from our depot, so we combine it with Rockhampton collections. We confirm a day with you when we quote.",
    ],
    faqs: [
      {
        question: "Do you collect from Yeppoon and Emu Park?",
        answer: "Yes. Yeppoon, Emu Park, Cooee Bay, Zilzie, Keppel Sands and the rest of the Capricorn Coast are included. Call 0422 360 534 and we will confirm a day.",
      },
      {
        question: "Can you collect from Great Keppel Island?",
        answer: "No. We collect from the mainland. If a vehicle is on an island, it needs to be on the mainland for us to collect it.",
      },
    ],
    nearby: ["rockhampton", "gladstone"],
  },
];
